version: "3.8"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8085:8080"
    command: start-dev

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - product
      - orders
      - inventory
      - keycloak

  product:
    build:
      context: ./product
    container_name: product
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  orders:
    build:
      context: ./orders
    container_name: orders
    ports:
      - "8181:8181"
    depends_on:
      - kafka
      - schema-registry

  inventory:
    build:
      context: ./inventory-service
    container_name: inventory
    ports:
      - "8082:8082"

  notification:
    build:
      context: ./notification-service
    container_name: notification
    depends_on:
      - kafka
      - schema-registry
    restart: always

  mongo:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data/mongo:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"

